# -*- coding: utf-8 -*-
"""Birth Rate Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TqGXe0jcq_hvhrBRFVGrZCSp0W0mmZwj
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv('births.csv')
dataset.head()

dataset.info()

missing_values = dataset.isnull().sum()
print(missing_values)

missing_percentage = pd.DataFrame(dataset.isnull().sum()*100/dataset.shape[0]).reset_index()
print(missing_percentage)

dataset['decade'] = 10 * (dataset['year'] // 10)
dataset.pivot_table('births', index='decade', columns='gender', aggfunc='sum')

dataset.head()

sns.set()
birth_decade = dataset.pivot_table('births', index='decade', columns='gender', aggfunc='sum')
birth_decade.plot()
plt.ylabel("Births per year")
plt.show()

quartiles = np.percentile(dataset['births'], [25, 50, 75])
mu = quartiles[1]
sig = 0.74 * (quartiles[2] - quartiles[0])

dataset = dataset.query('(births > @mu - 5 * @sig) & (births < @mu + 5 * @sig)')
dataset['day'] = dataset['day'].astype(int)
dataset.index = pd.to_datetime(10000 * dataset.year +
                              100 * dataset.month +
                              dataset.day, format='%Y%m%d')

dataset['dayofweek'] = dataset.index.dayofweek

dataset.pivot_table('births', index='dayofweek',
                    columns='decade', aggfunc='mean').plot()
plt.gca().set_xticklabels(['Mon', 'Tues', 'Wed', 'Thurs', 'Fri', 'Sat', 'Sun'])
plt.ylabel('mean births by day');
plt.show()

births_month = dataset.pivot_table('births', [dataset.index.month, dataset.index.day])
print(births_month.head())

births_month.index = [pd.datetime(2012, month, day)
                      for (month, day) in births_month.index]
print(births_month.head())

fig, ax = plt.subplots(figsize=(12, 4))
births_month.plot(ax=ax)
plt.show()